config/routes.rb
# -*- encoding : utf-8 -*-
Wtasystem::Application.routes.draw do
  resources :reports


   namespace :api , defaults: {format: 'json'} do
     namespace :v1 do
      resources :contracts
     end
   end

  match '/reports/time' => "reports#time"
  match "Working/503-error", :to => "working#maintenance_error"

  match "Working/503", :to => "working#maintenance"

  match "Working/500", :to => "working#error"

  match "Working/404", :to => "working#not_found"
   root to: "contracts#index"
  ActiveAdmin.routes(self)

resources :actnotes, :managements, :contracts, :messages, :actcodes, :incoming_mails,:quotes,:messages
devise_for :users, controllers: {sessions: 'devise/sessions',:confirmations => "confirmations"}, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' },skip: [:sessions]

devise_scope :user do
                 get 'signin'  => 'devise/sessions#new', as: :new_user_session
                 post 'signin' => 'devise/sessions#create', as: :user_session
                 get 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
                  #match "register" => "devise/registrations#new", as: :new_user_registration
                   match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation

               end

resources :users
   root to: "contracts#index"
   match '/confirmjob', to: "contracts#confirmjob"
   match '/emailjobwithnetonly', to: "contracts#emailjobwithnetonly"
   match '/emailjobwithallmoney', to: "contracts#emailjobwithallmoney"
   match '/emailjobnomoney', to: "contracts#emailjobnomoney"
   match '/confirmjob', to: "contracts#confirmjob"
   match '/otheracts', to: "contracts#otheracts"
   match '/import', to: "contracts#import_contracts"
   match '/alljobs', to: "contracts#alljobs"
   match '/missingrecords', to: "contracts#missingrecords"
  # match '/mailchimp', to: "contracts#mailchimp"
   match '/calendar', to: "contracts#calendar"
   #match '/exportcal', to: "incoming_mails#exportevents"
   #match '/gmail', to: "contracts#gmail"
   #match 'db/authorize', controller: 'dropbox', action: 'authorize'
   #match 'db/upload', controller: 'dropbox', action: 'upload'
   match '/incoming', to: "incoming_mails#create"
   match '/report', to: "contracts#report"

end

app/views/shared/_cal.html.erb
<table class="calendar">
    <% (1..days_in_month(10,31)).to_a.in_groups_of(7) do |group| %>
    <tr>
        <% group.each do |day| %>
        <td><%= day %></td>
        <% end %>
    </tr>
    <% end %>
    </table>

app/views/shared/_menubar.html.erb
<% if user_signed_in? %>
<!-- <h2 class="bigger"><%#= @managements.name %></h2> -->
<h2 class="maroon bigg">Welcome <%= current_user.fullname %></h2>
<% unless @message.nil? %>
<h6><%= @message.title %></h6>
<p><%= @message.body %></p>

<div id="tabstrip">
    <%= tabs_tag  do |tab| %>
    <%= tab.contract 'Dashboard', contracts_path %>
<% if can? :everything, @contract %>
    <%= tab.user 'Users', users_path %>
    <%= tab.message 'Messages', messages_path %>
<% end %>
    <%= tab.account   'Account', edit_user_path(current_user) %>
<% end %>
<% end %>
<% end %>
</div>

app/views/shared/_sidebar.html.erb
<nav id="main-nav">
<ul class="nav nav-list">
<%= render 'loginmenu' %>

</ul>
</nav>
</section>