config/routes.rb
# -*- encoding : utf-8 -*-
Wtasystem::Application.routes.draw do
  resources :reports


   namespace :api , defaults: {format: 'json'} do
     namespace :v1 do
      resources :contracts
     end
   end

  match '/reports/time' => "reports#time"
  match "Working/503-error", :to => "working#maintenance_error"

  match "Working/503", :to => "working#maintenance"

  match "Working/500", :to => "working#error"

  match "Working/404", :to => "working#not_found"
   root to: "contracts#index"
  ActiveAdmin.routes(self)

resources :actnotes, :managements, :contracts, :messages, :actcodes, :incoming_mails,:quotes,:messages
devise_for :users, controllers: {sessions: 'devise/sessions',:confirmations => "confirmations"}, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' },skip: [:sessions]

devise_scope :user do
                 get 'signin'  => 'devise/sessions#new', as: :new_user_session
                 post 'signin' => 'devise/sessions#create', as: :user_session
                 get 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
                  #match "register" => "devise/registrations#new", as: :new_user_registration
                   match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation

               end

resources :users
   root to: "contracts#index"
   match '/confirmjob', to: "contracts#confirmjob"
   match '/emailjobwithnetonly', to: "contracts#emailjobwithnetonly"
   match '/emailjobwithallmoney', to: "contracts#emailjobwithallmoney"
   match '/emailjobnomoney', to: "contracts#emailjobnomoney"
   match '/confirmjob', to: "contracts#confirmjob"
   match '/otheracts', to: "contracts#otheracts"
   match '/import', to: "contracts#import_contracts"
   match '/alljobs', to: "contracts#alljobs"
   match '/missingrecords', to: "contracts#missingrecords"
  # match '/mailchimp', to: "contracts#mailchimp"
   match '/calendar', to: "contracts#calendar"
   #match '/exportcal', to: "incoming_mails#exportevents"
   #match '/gmail', to: "contracts#gmail"
   #match 'db/authorize', controller: 'dropbox', action: 'authorize'
   #match 'db/upload', controller: 'dropbox', action: 'upload'
   match '/incoming', to: "incoming_mails#create"
   match '/report', to: "contracts#report"

end

app/views/show/_actnotes.html.erb
<% unless  contract.act_notes == "nil" %>
<div class="ui piled segment">
    <div class="ui top attached black label">Act Notes
    </div><br>

                   <p> <%= contract.act_notes %></p>
</div>
<% end %>

app/views/show/_address.html.erb
                    <% if contract.location_name? %>
                    <address>
                    <strong>Event Location</strong><br>
                     <strong>  <%= contract.location_name.gsub('"', ' ') %></strong><br>
                      <%= "#{contract.location_address_line_1}" %> <br> <%= "#{contract.location_city} #{contract.location_state} #{contract.location_zip}" %><br>
                        Phone: <%= contract.location_phone %>
                        <% end %><br><br>
                    <address>
                        <%= button_to("Get Directions", "http://maps.google.com/maps?saddr=My Location&daddr=#{themap}", class: 'ui button green success')%>

app/views/show/_agent.html.erb
<div class="ui fluid form segment">
           <div class="ui top attached black label">Agent Section
           </div>
<%= content_tag(:dt,"Contract number:     #{contract.contract_number}")  unless contract.contract_number.blank? %>

<%= content_tag(:dt,"Agent :              #{contract.agent}")  unless contract.agent.blank? %>
<%= content_tag(:dt,"Pickup Amount:              #{number_to_currency(contract.pick_up_amount)}")  unless contract.pick_up_amount.blank? || 0 %>
<%= content_tag(:dt,"Referral Fee Paid To:              #{number_to_currency(contract.referral_fee_to)}")  unless contract.referral_fee_to.blank? || 0 %>
       </div>

app/views/show/_buttons.html.erb
<% if current_user.is? :manager %>
<%   if contract.confirmation == 0 && contract.date_of_event < Date.today + 11.days %>
  <%=   link_to ' CONFIRM THIS EVENT ', confirmjob_path(id: contract.id), class: 'ui red button'%>
<% end %>
<div class="ui relaxed divided list">
<div class="item">

<div class="content">
    <%= link_to 'Email Job Info - All Money', emailjobwithallmoney_path(id: contract.id), class: 'tiny item' %></br>
</div></div>
    <%= link_to 'Email Job Info With Net Money', emailjobwithnetonly_path(id: contract.id), class: 'small item' %></br>
    <%= link_to 'Email Job Info Without Money', emailjobnomoney_path(id: contract.id), class: 'item' %>

<% else %>





<% if contract.date_of_event < Date.today + 11.days %>
<div class="ui raised segment">
       <div class="ui top attached red label">Email Job Info
       </div>
<br />
   <%   if contract.confirmation == 0 %>
   <%=   link_to ' CONFIRM THIS EVENT ', confirmjob_path(id: contract.id), class: 'ui red button'%>
    <%  else %>
   <% if current_user.is? :manager %>
<div class="ui relaxed divided list">
<div class="item">

<div class="content">
    <%= link_to 'Email Job Info - All Money', emailjobwithallmoney_path(id: contract.id), class: 'tiny item' %></br>
</div></div>
    <%= link_to 'Email Job Info With Net Money', emailjobwithnetonly_path(id: contract.id), class: 'small item' %></br>
    <%= link_to 'Email Job Info Without Money', emailjobnomoney_path(id: contract.id), class: 'item' %>
  <% elsif current_user.is? :no_money %>
<%= link_to 'Email Job Information', emailjobnomoney_path(id: contract.id), class: 'item' %></br>
 <% elsif current_user.is? :gross %>
<%= link_to 'Email Job Info - All Money', emailjobwithallmoney_path(id: contract.id), class: 'tiny item' %></br>
<%= link_to 'Email Job Information / Net Money', emailjobwithnetonly_path(id: contract.id), class: 'item' %></br>
 <%= link_to 'Email Job Information Without Money', emailjobnomoney_path(id: contract.id), class: 'item' %>
<% else %>
 <%= link_to 'Email Job Information / Net Money', emailjobwithnetonly_path(id: contract.id), class: 'item' %></br>
  <%= link_to 'Email Job Information Without Money', emailjobnomoney_path(id: contract.id), class: 'item' %>
    <% end %>
</div></div>

<% end %>
<% end %>
<% end %>

app/views/show/_clientextra.html.erb
<div class="span4 white thumbnail margintop">
<h3 class="sectionheaders"><span>Client Section</span></h3>
<dt>    Client Info:</dt> <%= contract.first_name %> <%= contract.last_name %><br>
<dt>    Email Address:</dt> <%= contract.email_address %><br>
<dt>    Bride / Bat Mitzvah Name:</dt> <%= contract.brides_names %><br>
<dt>    Grooms / Bar Mitzvah Name: </dt> <%= contract.grooms_name %><br>
<dt>    Home Phone:</dt> <%= contract.home_phone %><br>
<dt>    Work Phone:</dt> <%= contract.work_phone %><br>
<dt>    Cell Phone:</dt> <%= contract.cell_phone %>
</div>
<div class="span4 white thumbnail margintop">
<h3 class="sectionheaders"> <span>Extras Section</span></h3>

<dt>Early setup Time:</dt> <%= contract.early_setup_time %><br>
<dt>Giveaways:</dt> <%= contract.giveaways %><br>
<dt>Type of Light Show :</dt> <%= contract.type_of_light_show %><br>
<dt> Number of Horns:</dt> <%= contract.number_of_horns %><br>
<dt>Number of Dancers:</dt> <%= contract.number_of_dancers %><br>
<dt>Pick up Reason</dt> <%= contract.explanation_opf_pickup_adjustment %><br>
<%= contract.capital_music_player %><br>
<%= contract.questionnaire_received_date %><br>
<dt>  Referral Fee to :</dt> <%= contract.referral_fee_to %><br>
<dt>  Song Requests: </dt> <%= contract.song_requests %><br>
<dt>  Cocktail Instrumentation: </dt> <%= contract.cocktail_instrumentation %><br>
<dt>  Cocktail Time: </dt> <%= contract.cocktail_time %><br>
<dt>  Company:</dt> <%= contract.company %>
</div>

app/views/show/_clientextra.mobile.erb
<div class="span4 white thumbnail margintop">
<h3 class="sectionheaders"><span>Client Section</span></h3>
<dt>    Client Info:</dt> <%= contract.first_name %> <%= contract.last_name %><br>
<dt>    Email Address:</dt> <%= contract.email_address %><br>
<dt>    Bride / Bat Mitzvah Name:</dt> <%= contract.brides_names %><br>
<dt>    Grooms / Bar Mitzvah Name: </dt> <%= contract.grooms_name %><br>
<dt>    Home Phone:</dt> <%= contract.home_phone %><br>
<dt>    Work Phone:</dt> <%= contract.work_phone %><br>
<dt>    Cell Phone:</dt> <%= contract.cell_phone %>
</div>
<div class="span4 white thumbnail margintop">
<h3 class="sectionheaders"> <span>Extras Section</span></h3>

<dt>Early setup Time:</dt> <%= contract.early_setup_time %><br>
<dt>Giveaways:</dt> <%= contract.giveaways %><br>
<dt>Type of Light Show :</dt> <%= contract.type_of_light_show %><br>
<dt> Number of Horns:</dt> <%= contract.number_of_horns %><br>
<dt>Number of Dancers:</dt> <%= contract.number_of_dancers %><br>
<dt>Pick up Reason</dt> <%= contract.explanation_opf_pickup_adjustment %><br>
<%= contract.capital_music_player %><br>
<%= contract.questionnaire_received_date %><br>
<dt>  Referral Fee to :</dt> <%= contract.referral_fee_to %><br>
<dt>  Song Requests: </dt> <%= contract.song_requests %><br>
<dt>  Cocktail Instrumentation: </dt> <%= contract.cocktail_instrumentation %><br>
<dt>  Cocktail Time: </dt> <%= contract.cocktail_time %><br>
<dt>  Company:</dt> <%= contract.company %>
</div>

app/views/show/_contractinfo.html.erb
<%= content_tag_for(:dt, contract) do  %>
             <%= content_tag(:dt,"Date of Event:                 #{contract.date_of_event}") unless contract.date_of_event.blank? %>
             <%= content_tag(:dt,"Event Time:                    #{contract.eventtime}")  unless contract.eventtime.blank? %>
             <%= content_tag(:dt, "Early setup Time              #{contract.early_setup_time}") unless contract.early_setup_time.blank? %>
             <%= content_tag(:dt,"Event Type:                    #{contract.type_of_event}") unless contract.type_of_event.blank? %>
             <%= content_tag(:dt,"Reception Location:            #{contract.reception_location}") unless contract.reception_location.blank? %>
             <%= content_tag(:dt,"Contract Status:               #{contract.contract_status}")  unless contract.contract_status.blank? %>
             <%= content_tag(:dt,"Operating as:                  #{contract.type_of_act}")  unless contract.type_of_act.blank? %>
             <%= content_tag(:dt,"Form of:                       #{contract.act_form}")  unless contract.act_form.blank? %>
             <% if can? :see_money, @contracts %>
             <%= content_tag(:dt,"Contract Price:                #{number_to_currency(contract.contract_price)}") unless  self.blank? || contract.contract_price == 0 %>
             <% elsif %>
             <%= content_tag(:dt,"Contract Price:                #{number_to_currency(contract.act_net)}") unless  self.blank? || contract.act_net == 0 %>

             <% end %>

<% end %>

app/views/show/_mainandmap.mobile.erb
<div class="span5 white thumbnail"><h2>Activites</h2>
    <h2><%= contract.type_of_event %></h2>
    <h4>Operating as: <%= contract.type_of_act %></h4>
    <h4><%= contract.act_form %></h4>
    <h4>Agent : <%= contract.agent %> </h4>
    <h4>Reception Location: <%= contract.reception_location %></h4>
    <h5 class="padding15 textindent">Contract Status: <%= contract.contract_status %></h5>
    <hr>
    <h4 class="yesido"> <b>Date of event: </b><%= contract.date_of_event.to_formatted_s(:eventdate) %>  </h4>
    <h4 class="yesido"> <b>Event Time: </b><%= contract.eventtime %>    </h4>
    <h5 class="blue">Contract number: <%= contract.contract_number %></h5>
    <h4 class="green">Pickup Amount: <%= number_to_currency(contract.pick_up_amount) %></h4>
   <% if can? :see_money, @contracts %>
  <h4 class="green">Contract price: <%= number_to_currency(contract.contract_price)  %></h4>
   <% end %>
   <% unless current_user.is? :no_money %>
 <h4 class="green">Contract Net: <%= number_to_currency(contract.act_net) %></h4>
<% end %>

</div>

<div class="span3 white thumbnail">
<% if contract.location_name? %>
    <img src="http://maps.google.com/maps/api/staticmap?center=<%= themap %>&zoom=15&size=275x275&maptype=roadmap&sensor=true&markers=<%= themap %>" alt="Static Map for Events"></img><br>
    <h3> <span>Event Location</span></h3>
    <%= contract.location_name %><br>
    <%= "#{contract.location_address_line_1}" %> <br> <%= "#{contract.location_city} #{contract.location_state} #{contract.location_zip}" %><br>
    Phone: <%= contract.location_phone %>
    <% end %><br><br>
    <%= button_to("Get Directions", "http://maps.google.com/maps?saddr=My Location&daddr=#{themap}", class: 'btn-success')%>
</div>

app/views/show/_moneysection.html.erb
<div class="ui raised segment">
     <div class="ui top attached red label">Money
     </div>
<div class="ui list">
    <%= content_tag (:div), :class => "dl-horizontal" do %>
<%= content_tag(:div,"Contract Price :              #{number_to_currency(contract.contract_price)}")  unless self.blank? || contract.contract_price == 0  %><br>
<%#= content_tag(:div,"Act Gross:            #{number_to_currency(contract.act_gross)}") unless  self.blank? || contract.act_gross == 0 %>
<%= content_tag(:div,"Act Net:            #{number_to_currency(contract.act_net)}") unless  self.blank? || contract.act_net == 0 %>
<%= content_tag(:div,"cocktails charge:            #{number_to_currency(contract.cocktails_charge)}") unless  self.blank? || contract.cocktails_charge == 0 %>
<%= content_tag(:div,"ceremony charge:             #{number_to_currency(contract.ceremony_charge)}") unless self.blank? || contract.ceremony_charge == 0 %>
<%= content_tag(:div,"early setup charge:          #{number_to_currency(contract.early_setup_charge)}") unless self.blank? || contract.early_setup_charge == 0 %>
<%= content_tag(:div,"charge per horn:             #{contract.number_of_horns}"  " @"  "#{number_to_currency(contract.charge_per_horn)}") unless self.blank? || contract.number_of_horns == 0 %>
<%= content_tag(:div,"other charges:               #{number_to_currency(contract.other_charges)}") unless self.blank? || contract.other_charges == 0 %>
<%= content_tag(:div,"charge per dancer:           #{contract.number_of_dancers}"  " @"  "#{number_to_currency(contract.charge_per_dancer)}") unless self.blank? || contract.number_of_dancers == 0 %>
<%= content_tag(:div,"giveaways charge:            #{number_to_currency(contract.giveaways_charge)}") unless self.blank? || contract.giveaways_charge == 0 %>
<%= content_tag(:div,"dj tech_charge:              #{number_to_currency(contract.dj_tech_charge)}") unless self.blank? || contract.dj_tech_charge == 0 %>
<%= content_tag(:div,"non-commission charges:  #{number_to_currency(contract.non_commissionable_charges)}") unless self.blank? || contract.non_commissionable_charges == 0 %>
<%#= content_tag(:div,"capital music pay:           #{number_to_currency(contract.capital_music_pay)}") unless self.blank? || contract.capital_music_pay == 0 %>
<%= content_tag(:div,"base price of act:           #{number_to_currency(contract.base_price_of_act)}") unless self.blank? || contract.base_price_of_act == 0  %>
<%= content_tag(:div,"referral fee amount:         #{number_to_currency(contract.referral_fee_amount)}") unless self.blank? || contract.referral_fee_amount == 0   %>
<%= content_tag(:div,"tax amount:                  #{number_to_currency(contract.tax_amount)}") unless self.blank? || contract.tax_amount == 0 %>
<% end %>
</div>
</div>

app/views/show/_players.html.erb
<% unless contract.videographer_1.blank? && contract.videographer_2.blank? %>
<div class="ui fluid form segment">
       <div class="ui top attached black label">Players Section
       </div><br>
<%= content_tag(:div,"Player 1:   #{contract.videographer_1}") %>
<%= content_tag(:div,"Player 2:   #{contract.videographer_2}") %>
<%= content_tag(:div,"Player 3:   #{contract.videgrapher_3}") %>
<%= content_tag(:div,"Player 4:   #{contract.player4}") %>
<%= content_tag(:div,"Player 5:   #{contract.player5}") %>
<%= content_tag(:div,"Player 6:   #{contract.player6}") %>
<%= content_tag(:div,"Player 7:   #{contract.player7}") %>
<%= content_tag(:div,"Player 8:   #{contract.player8}") %>
<hr class="show-line">
</div>
<% end %>

app/views/show/_provision.html.erb
<% unless contract.contract_provisions == "nil" %>
<div class="ui small piled feed segment stackable">
    <div class="ui top attached black label">Contract Provisions
    </div><br>
            <h3><span>Contract Provisions</span></h3>

                <%=  contract.contract_provisions.gsub('"', ' ') unless contract.contract_provisions.blank? %>

</div>
<% end %>

app/views/show/_provision.mobile.erb
<div class="span8 white thumbnail margintop">
            <h3 class="sectionheaders"><span>Contract Provisions</span></h3>
                <% unless contract.contract_provisions == "nil" %>
                <%=  contract.contract_provisions.gsub('"', ' ') unless contract.contract_provisions.blank? %>
                <% end %>
            <h3 class="sectionheaders"><span>Act Notes</span></h3>
                <% unless  contract.act_notes == "nil" %>
                    <%= contract.act_notes %>
                <% end %>
            <h3 class="sectionheaders"><span>All Services Provided</span></h3>
            <ul>
            <% unless @additional.blank? %>
            <% @additional.each do |addi| %>

            <% if current_user.is? :everything %>
            <li><%= link_to "#{addi.act_booked} - #{addi.type_of_act} - #{addi.act_form}", addi %></li>
            <% else %>
            <li><%= "#{addi.act_booked} - #{addi.type_of_act} - #{addi.act_form} - #{addi.eventtime}" %></li>
            <% end %>
            <% end %>
            <% end %>
            </ul>
</div>

app/views/show/_version.html.erb
<h3>Whats Changed</h3>
<%#= @versions.last.changeset if @versions.last %>
<% if @versions.last  %>
<%#= @versions.count %>
<% @versions.last.changeset.each do |key, value| %>
  <li><%=  "#{key.humanize} to #{value[1]}" %></li>
<% end %>
<% end %>
<hr>

app/views/show/_weddingstuff.html.erb
<% unless contract.ceremony_start_time.blank? && contract.ceremonoy_location_name.blank? %>
  <div class="ui fluid form segment">
        <div class="ui top attached black label">Wedding Section
        </div><br>
<%= content_tag(:div,"Ceremony Date:           #{contract.date_of_ceremony}")%>
<%= content_tag(:div,"Ceremony Location:       #{contract.ceremonoy_location_name}") %>
<%= content_tag(:div,"Ceremony Address:        #{contract.ceremonoy_address_line_1}") %>
<%= content_tag(:div,"Ceremony Address line 2: #{contract.ceremony_address_line_2}") %>
<%= content_tag(:div,"Ceremony City:           #{contract.ceremony_location_city}") %>
<%= content_tag(:div,"Ceremony State:          #{contract.seremonly_location_state}") %>
<%= content_tag(:div,"Ceremony Zip:            #{contract.ceremony_location_zip}") %>
<%= content_tag(:div,"Ceremony Start Time:     #{contract.ceremony_start_time}") %>
<%= content_tag(:div,"Ceremony Instrumentation:#{contract.ceremony_instrumenttation}") %>
</div>

<% end %>