config/routes.rb
# -*- encoding : utf-8 -*-
Wtasystem::Application.routes.draw do
  resources :reports


   namespace :api , defaults: {format: 'json'} do
     namespace :v1 do
      resources :contracts
     end
   end

  match '/reports/time' => "reports#time"
  match "Working/503-error", :to => "working#maintenance_error"

  match "Working/503", :to => "working#maintenance"

  match "Working/500", :to => "working#error"

  match "Working/404", :to => "working#not_found"
   root to: "contracts#index"
  ActiveAdmin.routes(self)

resources :actnotes, :managements, :contracts, :messages, :actcodes, :incoming_mails,:quotes,:messages
devise_for :users, controllers: {sessions: 'devise/sessions',:confirmations => "confirmations"}, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', sign_up: 'cmon_let_me_in' },skip: [:sessions]

devise_scope :user do
                 get 'signin'  => 'devise/sessions#new', as: :new_user_session
                 post 'signin' => 'devise/sessions#create', as: :user_session
                 get 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
                  #match "register" => "devise/registrations#new", as: :new_user_registration
                   match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation

               end

resources :users
   root to: "contracts#index"
   match '/confirmjob', to: "contracts#confirmjob"
   match '/emailjobwithnetonly', to: "contracts#emailjobwithnetonly"
   match '/emailjobwithallmoney', to: "contracts#emailjobwithallmoney"
   match '/emailjobnomoney', to: "contracts#emailjobnomoney"
   match '/confirmjob', to: "contracts#confirmjob"
   match '/otheracts', to: "contracts#otheracts"
   match '/import', to: "contracts#import_contracts"
   match '/alljobs', to: "contracts#alljobs"
   match '/missingrecords', to: "contracts#missingrecords"
  # match '/mailchimp', to: "contracts#mailchimp"
   match '/calendar', to: "contracts#calendar"
   #match '/exportcal', to: "incoming_mails#exportevents"
   #match '/gmail', to: "contracts#gmail"
   #match 'db/authorize', controller: 'dropbox', action: 'authorize'
   #match 'db/upload', controller: 'dropbox', action: 'upload'
   match '/incoming', to: "incoming_mails#create"
   match '/report', to: "contracts#report"

end

app/models/management.rb
# -*- encoding : utf-8 -*-
class Management < ActiveRecord::Base
    has_many :users
    belongs_to :user
   default_scope order: 'name ASC'
end

app/controllers/managements_controller.rb
# -*- encoding : utf-8 -*-
class ManagementsController < InheritedResources::Base
  load_and_authorize_resource
 respond_to :html, :xml, :json
end

app/views/managements/_form.html.erb
<%= form_for(@management) do |f| %>
  <% if @management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@management.errors.count, "error") %> prohibited this management from being saved:</h2>

      <ul>
      <% @management.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manageagement_code %><br />
    <%= f.text_field :manageagement_code %>
  </div>
  <div class="actions">
    <%= f.submit button_html: { class: 'button button_green' } %>
  </div>
<% end %>

app/views/managements/edit.html.erb
<h1>Editing management</h1>

<%= render 'form' %>

<%= link_to 'Show', @management %> |
<%= link_to 'Back', managements_path %>

app/views/managements/index.html.erb
<div class="sheet sheet-condensed">
  <div class="sheet-inner">
<table cellpadding="0" cellspacing="0" class="table" width="100%">
    <thead class="sTableHead">
  <tr> <th class="head0">Management ID</th>
    <th class="head0">Name</th>
    <th class="head0">Manageagement code</th>

    <th class="head0"></th>
    <th class="head0"></th>
    <th class="head0"></th>
  </tr> button
    </thead>
<% @managements.each do |management| %>
  <tr>  <td><%= management.id %></td>
    <td><%= management.name %></td>
    <td><%= management.manageagement_code %></td>

    <td><%= link_to 'Show', management %></td>
    <td><%= link_to 'Edit', edit_management_path(management) %></td>
  <td><%= link_to 'Destroy', management, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>

</table>

<br />
</div></div>
<%= button_to 'New Management', new_management_path(@managemment), class: 'button button_blue', method: :get %>

app/views/managements/new.html.erb
<h1>New management</h1>

<%= render 'form' %>

<%= button_to 'Back', managements_path, action: "new", method: :put, class: 'button button_blue',method: :get %>

app/views/managements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @management.name %>
</p>

<p>
  <b>Manageagement code:</b>
  <%= @management.manageagement_code %>
</p>


<%= link_to 'Edit', edit_management_path(@management) %> |
<%= link_to 'Back', managements_path %>